"use client"
import "~/styles/globals.css";
import { Poppins } from "next/font/google";
import Header from "~/components/Header/Header";
import CopyRightFooter from "~/components/Footer/CopyRightFooter";
import Footer from "~/components/Footer/Footer";
import Expertise from "~/components/Expertise";
import GetStarted from "~/components/GetStarted";
import Testimonials from "~/components/Testimonials";
import { QueryClientProvider } from "@tanstack/react-query";
import client from "~/utils/client";
import ContactModal from "~/components/ContactModal";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/images/favicon.webp" }],
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <div className="page_content">
          <Header />
          <ContactModal />
          {children}
          <Expertise />
          <GetStarted />
          <Testimonials />
          <Footer />
          <CopyRightFooter />
      </div>
  );
}
